global.editorModes = [
    {name: 'JavaScript', mime: 'text/javascript', mode: 'javascript', ext: 'js' },
    {name: 'Plain Text', mime: 'text/plaintext', mode: 'null', ext: '' },
    {name: 'HTML', mime: 'text/html', mode: 'htmlmixed', ext: "html"},
    {name: "CSS", mime: "text/css", mode: "css", ext: "css"},
    {name: "Sass", mime: "text/x-sass", mode: "sass", ext: "sass"},
    {name: "Python", mime: "text/x-python", mode: "python", ext: "py"},
    {name: "VB.NET", mime: "text/x-vb", mode: "vb", ext: "vb"},
    {name: "VBScript", mime: "text/vbscript", mode: "vbscript", ext: "vbs"},
    {name: "Ruby", mime: "text/x-ruby", mode: "ruby", ext: "rb"},
    {name: "SQL", mime: "text/x-sql", mode: "sql", ext: "sql"},
    {name: "PHP", mime: "text/x-php", mode: "php", ext: "php"},
    {name: "C", mime: "text/x-csrc", mode: "clike", ext: "c"},
    {name: "Pascal", mime: "text/x-pascal", mode: "pascal", ext: "pas"},
    {name: "PowerShell", mime: "application/x-powershell", mode: "powershell", ext: "ps1"},
    {name: "Shell", mime: "text/x-sh", mode: "shell", ext: "sh"},
];
